hamlet-io/docker-hamlet

images/stretch/Dockerfile, utilities/codeontap/Dockerfile
Environment variable GENERATION_PLUGIN_DIRS is already used by CodeOnTap during template creation. This PR will set this variable to existing plugins directory, allowing the lookup to occur without additional configuration.
``` Existing usage within createTemplate.sh
${GENERATION_DIR}/freemarker.sh \
-d "${template_dir}" \
${GENERATION_PRE_PLUGIN_DIRS:+ -d "${GENERATION_PRE_PLUGIN_DIRS}"} \
-d "${GENERATION_BASE_DIR}/engine" \
-d "${GENERATION_BASE_DIR}/providers" \
${GENERATION_PLUGIN_DIRS:+ -d "${GENERATION_PLUGIN_DIRS}"} \
-t "${template}" \
-o "${template_result_file}" \
"${args[@]}" || return $?
```
Also added the Azure CLI to the pip installation packages.
=> Feat azure

images/stretch/hooks/build, images/stretch/hooks/push, scripts/azpipelines-agent/start, utilities/azure-pipelines/agent/Dockerfile
Impliments container images for an Azure Pipelines Agent. This can be used to undertake build or release workloads within Azure DevOps.
``` bash
docker run -e AZP_URL="https://dev.azure.com/myAwesomeCompany/" -e AZP_TOKEN="1234567890" -e AZP_AGENT_NAME=MyAwesomeAgent azpipeline
```
When terminated unexpectedly the Agent will remain in the Agent Pool within Azure DevOps. It will then potentially be allocated work to do long after the container is destroyed. When shut-down through `"docker stop <container-name"` however, the agent is cleaned up from the server.
=> Feature - Azure Pipelines Agent

utilities/azure-pipelines/agent/Dockerfile
These were not required to be fixed values.
=> Updated UID/GID so they are not clashing with jenkins. 

images/stretch/hooks/build
Az pipelines meteor build was pointing at the az pipelines Dockerfile and not the meteor one.
=> corrected az pipelines meteor build to run the meteor dockerfile.

utilities/azure-pipelines/agent/Dockerfile
- UID of 1000 as standard
- GID of 115 for the docker group on Azure deployed container hosts
=> Az Pipelines docker settings

images/stretch/Dockerfile
Presently all calls to the Az CLI are accompanied by a warning message that two dependencies are on unsupported versions. This has been identified on the az-cli github page (Azure/azure-cli#9257) as an issue with the pip installer method specifically, where the dependencies have not been pinned to a specific version. The resolution method for now is to reinstall "requests" package through pip, which identifies the correct dependencies and reverts to them.
At a later stage, once the az-cli pip installation method has its dependencies correctly set we can remove this.
Example warning message:
```
(Info) [2019-11-07_00:05:39] Provisioning State is "Running".
(Info)     Retry in 30 seconds...
/usr/local/lib/python3.5/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 …
```
=> resolving az-cli dependency issues

images/stretch/Dockerfile
The Azure CLI uses some extensions to manage some of the lesser-used resources. The cli itself is used to perform the fetch/install of these extensions. This PR creates a new layer on the dockerfile that can be used for any future cli extensions used by codeontap.
=> Azure CLI Extensions

Jenkinsfile
Adds the quiet period back on for docker images. Since we have a number of repo's triggering docker builds and the docker build process always clones from a tag or the latest master branch we don't need to build the docker image on every commit, just at the end of a window of gen3 activity
=> <fix>Reduce docker image overlap builds

Jenkinsfile, images/stretch/Dockerfile, images/stretch/hamlet/Dockerfile
A couple of minor fixes following on from #22 
- Move the Environment variables and Build args for the hamlet install process over to the base image 
- Move the Cli into the base image - this isn't used by our automation processes at the moment but should be available 
Also moves our node install from Apt-get packages over to nodenv inline with the installation of our other programming languages ( python and ruby )
=> <fix> Consolidated docker build

scripts/jenkins-jnlp-agent/jenkins-agent
allows for short env var based scripts to be run before the jnlp agent is started. This allows for on boot configuration for git or other tools
=> feat: support startup commands as env vars

images/stretch/Dockerfile
Move the Azure CLI Extensions directory somewhere available to all accounts.
Extensions were not accessible to the `hamlet` user when another image is built from this. The `root` user installs the extension so the extension which defaults to $HOME/.azure/... - setting the global variable AZURE_EXTENSION_DIR overrides this.
=> Fix - Azure CLI Extensions Directory

config.json, images/stretch/Dockerfile, scripts/base/build_hamlet.sh
- Load the `diagrams` plugin into the Hamlet Deploy Engine as a standard feature
- When cloning remote repositories, allow for a "default" branch of `master` or `main`
hamlet-io/executor-python#75
local container build and check env var + plugin dir are as expected
=> Feature - Include Diagrams Plugin

images/stretch/Dockerfile, scripts/base/build_hamlet.sh
Update the clone configuration for hamlet build to handle tags, and main master branches for builds
Cloning of the hamlet repos were failing when using a version tag 
Tested locally
=> fix: handle git refs during build process

config.json, images/stretch/Dockerfile
Removes the startup script repo from hamlet docker image as it has now been deprecated 
Moves the startup functionality into the engine and allows for more flexible control over how scripts are handled
Tested locally
=> refactor: remove startup script repo

CHANGELOG.md, package.json
fix the url referenced in changelogs to align with each repo
Makes the changelog understandable
Tested locally
=> fix: repo url in changelog

config.json
Include the cmdb plugin in the image.
By including the cmdb plugin, it makes continued testing of its use easier given the auto-detection logic in the bash executor.
Note that because the cmdb plugin is not currently included in the `GENERATION_PLUGIN_DIRS` environment variable, dynamic cmdb processing won't be active by default, but simply by adding it as an extra path value to this variable, dynamic cmdb loading will be activated.
It hasn't - simple enough that any issues will be fixed following any issues in container build pipeline.
- None
- None
- None
=> feat: include cmdb plugin

config.json, images/stretch/Dockerfile, scripts/base/build_hamlet.sh
Updates the hamlet install process to use pip for the hamlet-cli instead of cloning and installing from the repo
This uses the deployment process we have now automated for the cli and aligns with best practice for python 
Tested locally 
- None
- None
- None
=> refactor: install hamlet-cli via pip

scripts/user_env/0_nodenv.sh
- Add nodenv plugins which handle the shim processing for global node packges. This adds a hook in npm which tells nodenv to update the available binaries on global installs
- Adds yarn and npm ( update ) as default packages for all node versions installed. This will be automatically done as part of the install process
Yarn should be a default package available under all installations since it is used to install and setup any app
Tested locally 
- None
- None
- None
=> fix: include plugins for global node packages

.github/workflows/build.yml
Remove caching for the docker build process
Docker caching only works if file contents change as part of the image and aren't affected by changes created by scripts.
Since this image is based on tool installs we should always rebuild the image without a cache. The image isn't built too often now so it won't really be an impact
Tested using workflow
- None
- None
- None
=> fix: remove docker layer caching

scripts/user_env/3_setup_hamlet.sh
Set the default hamlet engine to the tram release instead of unicycle
The tram release is nightly build of the hamlet engine which has been tested across a more stringent process than the unicycle engine which gets the latest updates from each individual source. 
This makes the hamlet container more friendly to new users and use in CI environments
Tested locally
- None
- None
- None
=> fix: set default engine to tram

Dockerfile, scripts/user_env/3_setup_hamlet.sh
Adds some basic smoke tests to make sure that hamlet has been installed as expected and that it is available for the container to use
We want to make sure basic things like the hamlet engine are available 
This was discovered as an issue in https://github.com/hamlet-io/executor-python/issues/177 
Tested locally 
None
- None
- None
- None
=> feat: add smoke tests for hamlet engine setup

.github/workflows/changelog.yml
Create a draft PR for changelog updates and enable CI to ensure that the changelog can be merged as required
Makes it easy to follow the changelog setup and removes some of the confusion around changelog generation
Tested on all other repos 
- None
- None
- None
=> fix(ci): create draft PR for changelog generation

Dockerfile
updates the jar file path to align with the changes added into the executors to align the environment variables with the other parts
Makes the configuration easier to follow and understand. Using a file path for the environment variable makes it easier to break each part up as required
Tested locally 
- https://github.com/hamlet-io/executor-bash/pull/236
- 
- None
- None
=> feat: rename bin file to align with executor updates

.github/workflows/build.yml
regression as copy paste error to use the dockerhub creds when pushing image
builds failing to push images
- None
- None
- None
=> fix: use dockerhub login

.github/workflows/build.yml
Fix syntax for startswith to not include an wildcard 
push on tag failing
- None
- None
- None
=> fix: tag tigger for push

.github/workflows/build.yml, Dockerfile
Use the scheduled builds to create a daily latest docker image that can be used in deployments that don't use the hamlet commands
To cater for existing implementations we need a docker image that contains the latest hamlet release without the use of the hamlet cli. The nightly build of the docker image will default to use the unicycle engine by default and create a latest build each night.
Will be tested in CI process
- None
- None
- None
=> feat: default to unicycle builds on schedules

.github/workflows/build.yml, scripts/user_env/0_nodenv.sh
Rely on the version of npm provided by node rather than always installing the latest.
Display more version information during the build.
This permits configurations a more deterministic expectation as to when they need to upgrade to new major versions of npm, such as upgrades to `package-lock.json` files.
Tested when PR submitted
- None
- None
- None
=> fix: match npm version to node version

scripts/meteor/setup_meteor.sh
Set environment variables to ignore certificate expiry issues when running meteor.
Fixes #67 
Because we are building an old version of meteor, it is necessary to turn off some certificate checking during container build.
Tested as part of build process
- None
- None
- None
=> fix: ignore meteor certificate issues

scripts/entrypoint.sh, scripts/jenkins-jnlp-agent/jenkins-agent, scripts/shim_setup.sh, scripts/user_env/0_pyenv.sh, scripts/user_env/0_rbenv.sh
- remove some of the set flags for exception handling
Overly configured set commands were causing issues with container startup and executing scripts that were not built for the configuration
tested locally
- None
- None
- None
=> fix: relax the set commands used in bash scripts

.github/workflows/build.yml, README.md
Move the hosting of the docker image from dockerhub to ghcr 
Makes it easier to manage our container image hosting as part of our overall Github organisation
Tested locally
- None
- None
- None
=> refactor: migrate to ghcr for hosting

.github/workflows/changelog.yml
Updates the shared github workflows used to the latest version
Resolves a bug in the changelog generation and moves to using the latest nodeJS version in the actions
- None
- None
- None
=> fix: move to standard changelog
