images/stretch/hooks/build

+ Corrected some inconsistencies between az image tag naming conventions in build & push scripts.
+ Corrected the base images for the Az images.

Fix Container Build after Az Build inclusions

---

images/stretch/Dockerfile
utilities/codeontap/Dockerfile

A couple of fixes 
- Install cli requirements before installing the cli 
- set a default entrypoint on the base image

<fix> cli requirements install

---

Jenkinsfile

Move to using multibranch jenkins plugin using multiple repo sources

<refactor> docker build to multibranch

---

config.json
utilities/codeontap/Dockerfile

Part of https://github.com/codeontap/gen3/issues/1022 
aligns the docker image build process with the new plugin setup

<refactor> aws plugin migration

---

config.json
utilities/codeontap/Dockerfile

Docker implementation of https://github.com/codeontap/gen3/issues/1231 
This updates the environment variables and docker clone scripts to align with the refactor

<refacotr> executor-engine split

---

config.json
utilities/codeontap/Dockerfile

align docker container with https://github.com/codeontap/executor-bash/pull/2

<refactor> bash executor consolidation

---

Jenkinsfile
README.md
config.json
images/stretch/builder/Dockerfile
images/stretch/builder/meteor/Dockerfile
images/stretch/builder/meteor/cache-packages/Dockerfile
scripts/base/build_codeontap.sh
utilities/azure-pipelines/agent/Dockerfile
utilities/codeontap/Dockerfile
utilities/jenkins/agent-jnlp/Dockerfile

Update docker image and repo cloning to use hamlet

<refactor> move to hamlet

---

images/stretch/Dockerfile
scripts/base/shellprompt.sh

Implemented a quality-of-life change to the container bash prompt, placing the current directory on its own line and making clear which branch of a git repo the user is currently viewing.
The primary use of the container is to work with hamlet CMDBs which are (typically) stored under git version control. Because hamlet operations are dependant on the working directory, often the current working directory is a particularly lengthy string. This can make it difficult to read output at times, particularly when debugging. It also means even short commands get word-wrapped within a terminal session which is similarly difficult to read.
Local image build
N/A

Feature - QOL - Prettier Bash Prompt

---

scripts/base/shellprompt.sh

Fix - Shell Prompt Spacing

---

images/stretch/Dockerfile

Adds support for accessing  the cookiecutter templates directory via an environment variable

feature: add patterns dir env var

---

images/stretch/Dockerfile
images/stretch/hamlet/Dockerfile

A couple of minor fixes 
- Align the Hamlet cli installation with its rename ( https://github.com/hamlet-io/executor-python/issues/38 ) 
- Create the bash prompt shell skeleton before the user is created

fix: hamlet cli installation and cli prompt

---

images/stretch/jenkins/agent-jnlp/Dockerfile

Updates the jenkins remoting agent to the latest version to catch bug fixed and the like

feature: update jenkins remoting version

---

images/stretch/Dockerfile

Cleanup hamlet install process to remove production requirements file
docker build process failing with packaging
Tested locally

fix: hamlet cli install

---

README.md
config.json
images/stretch/Dockerfile

- Removes the executor-cookiecutter repo from the docker image as this is now covered in the executor-python repo 
- Cleans up the README file after review for #38 
Less package requirements and dependencies 
- None
- None
- None

Remove patterns repo

---

.github/workflows/build.yml
Dockerfile
scripts/user_env/3_setup_hamlet.sh

- moves to using standard releases of the hamlet cli
- use the default engine version defined by the cli instead of overriding it
- add test to make sure that the engine can be called and generate outputs
- enable automatic updates of the engine to reduce the need to rebuild the container
- Use the standard install process to setup the engine
- move to using docker meta during CI builds to align with our other docker images and make tagging consistent
Makes the CLI and hamlet process easier to follow and makes the docker image more stable
Tested locally
- None
- None
- None

refactor: hamlet cli and engine management

---

.github/workflows/build.yml

Silly copy paste
Annoying me
- None
- None
- None

chore(ci): fix description on step name

---

.github/workflows/build.yml

add ci trigger for tags added to the repo 
Was missed during the migration to tagging
- None
- None
- None

fix: add tag trigger for ci build process

---

scripts/user_env/3_setup_hamlet.sh

Fix an issue with #62 where the testing failed on engine env lookup
Supports explicit configured engines
- None
- None
- None

fix: testing for handling explicit set engine vs global

---

.github/workflows/build.yml
Dockerfile
scripts/user_env/0_nodenv.sh
scripts/user_env/0_pyenv.sh
scripts/user_env/0_rbenv.sh
scripts/user_env/2_deploy_tools.sh
scripts/user_env/3_setup_hamlet.sh

- Breaking change (fix or feature that would cause existing functionality to change)
- Updates from the _global engine to using the shim engine
- Bump default versions for node, python and ruby
Aligns with the engine naming in latest version of the cli
TEsted locally
- None
- None
- None

feat: support changes to the cli with the shim engine

---

scripts/azpipelines-agent/start
scripts/entrypoint.sh
scripts/jenkins-jnlp-agent/jenkins-agent
scripts/setup_user_env.sh
scripts/shim_setup.sh

- use bash instead of sh for jenkins agent start up
Failure on task startup
Tested locally
- None
- None
- None

fix: update shell for jenkins agent

---

Dockerfile
scripts/user_env/0_jenv.sh

Minor updates to get the docker build working
keeping up with changes from dependent services
- None
- None
- None

fix: minor updates to docker image
